# Generated by Django 4.1.5 on 2023-04-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expire Time'),
        ),
    ]
