# Generated by Django 4.1.5 on 2023-04-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Expire Time'),
        ),
    ]
