version: "3.8"

services:
    app:
        build: './app'
        container_name: 'app'
        restart: 'always'
        expose:
            - '8000'
        volumes:
            - type: 'bind'
              source: './volumes/app'
              target: '/app'
        
        env_file:
            - ./volumes/app/.env
        environment:
            - "POSTGRES_DATABASE=${DB_NAME}"
            - "POSTGRES_USER=${DB_USER}"
            - "POSTGRES_PASSWORD=${DB_PASSWORD}"
            - "POSTGRES_HOST=db"
        depends_on:
            - db
            - nginx
    db:
        image: postgres:14
        container_name: 'iranigramdb'
        restart: 'always'
        expose:
            - '5432'
        environment:
            - "POSTGRES_DATABASE=${DB_NAME}"
            - "POSTGRES_USER=${DB_USER}"
            - "POSTGRES_PASSWORD=${vY8GjoENde2qgH}"
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - type: 'bind'
              source: './volumes/dbdata'
              target: '/var/lib/postgresql/data'
        
        env_file:
            - ./volumes/app/.env
    nginx:
        build: './nginx'
        container_name: 'nginx'
        restart: 'always'
        ports:
            - "8080:80"
        volumes:
            - type: 'bind'
              source: './volumes/ticket_files'
              target: '/app/ticket_files'
            
            - type: 'bind'
              source: './volumes/static'
              target: '/app/static'