# Generated by Django 4.1.5 on 2023-03-13 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('increase_ab_by_admin', 'increase_ab_by_admin'), ('decrease_ab_by_admin', 'decrease_ab_by_admin'), ('payment_for_order', 'payment_for_order'), ('add_fund', 'add_fund'), ('return_canceled_order_fee', 'return_canceled_order_fee'), ('return_partial_order_fee', 'return_partial_order_fee')], max_length=30, null=True)),
                ('price', models.IntegerField(blank=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('wallet', 'wallet'), ('online', 'online'), ('system', 'system')], max_length=300, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('order_id', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_gateway', models.CharField(blank=True, default='System', max_length=30)),
                ('payment_ref', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
