# Generated by Django 4.1.5 on 2023-04-19 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('increase_ab_by_admin', 'increase_ab_by_admin'), ('decrease_ab_by_admin', 'decrease_ab_by_admin'), ('payment_for_order', 'payment_for_order'), ('add_fund', 'add_fund'), ('return_canceled_order_fee', 'return_canceled_order_fee'), ('return_partial_order_fee', 'return_partial_order_fee')], max_length=30, null=True, verbose_name='Type of transaction')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Price')),
                ('balance', models.IntegerField(blank=True, null=True, verbose_name='Balance')),
                ('payment_type', models.CharField(blank=True, choices=[('wallet', 'wallet'), ('online', 'online'), ('system', 'system')], default='system', max_length=300, null=True, verbose_name='Payment Type')),
                ('details', models.CharField(blank=True, max_length=200, null=True, verbose_name='Details')),
                ('order_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Order Code')),
                ('payment_gateway', models.CharField(blank=True, default='system', max_length=30, verbose_name='Payment Gateway')),
                ('payment_ref', models.CharField(blank=True, max_length=30, null=True, verbose_name='Payment Ref')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
