# Generated by Django 4.1.5 on 2023-03-13 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transactions',
            name='balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='order_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_gateway',
            field=models.CharField(blank=True, default='System', max_length=30, verbose_name='Payment Gateway'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Payment Ref'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('wallet', 'wallet'), ('online', 'online'), ('system', 'system')], max_length=300, null=True, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(blank=True, choices=[('increase_ab_by_admin', 'increase_ab_by_admin'), ('decrease_ab_by_admin', 'decrease_ab_by_admin'), ('payment_for_order', 'payment_for_order'), ('add_fund', 'add_fund'), ('return_canceled_order_fee', 'return_canceled_order_fee'), ('return_partial_order_fee', 'return_partial_order_fee')], max_length=30, null=True, verbose_name='Type of transaction'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
