# Generated by Django 4.1.5 on 2023-04-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transactions_order_id_transactions_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_gateway',
            field=models.CharField(blank=True, default='system', max_length=30, verbose_name='Payment Gateway'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('wallet', 'wallet'), ('online', 'online'), ('system', 'system')], default='system', max_length=300, null=True, verbose_name='Payment Type'),
        ),
    ]
