# Generated by Django 4.1.5 on 2023-03-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_ticket_file_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('closed', 'closed'), ('pending', 'pending'), ('support answer', 'support answer'), ('user answer', 'user answer')], default='submitted', max_length=30, verbose_name='Status'),
        ),
    ]
