# Generated by Django 4.1.5 on 2023-03-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('closed', 'closed'), ('pending', 'pending'), ('support answer', 'support answer'), ('user answer', 'user answer')], max_length=30, verbose_name='Status'),
        ),
    ]
