# Generated by Django 4.1.5 on 2023-04-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Subject'),
        ),
    ]
