# Generated by Django 4.1.5 on 2023-03-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='order_id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='order_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Order Code'),
        ),
    ]
