# Generated by Django 4.1.5 on 2023-04-05 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_order_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Server Order Code')),
                ('order_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Order Code')),
                ('link', models.CharField(max_length=1000, verbose_name='Link')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('wallet_paid_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Wallet Paid Amount')),
                ('online_paid_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Online Paid Amount')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Cart'), ('wallet', 'Wallet')], default='balance', max_length=50, verbose_name='Payment Method')),
                ('status', models.CharField(blank=True, choices=[('Queued', 'Queued'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('In progress', 'In progress'), ('Canceled', 'Canceled'), ('Completed', 'Completed'), ('Partial', 'Partial'), ('Refunded', 'Refunded')], default='queued', max_length=30, null=True, verbose_name='Status')),
                ('start_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Start Count')),
                ('remains', models.PositiveIntegerField(blank=True, null=True, verbose_name='Remains')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.service', verbose_name='Service')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.servicetype', verbose_name='ServiceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
