# Generated by Django 4.1.5 on 2023-04-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_link_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Queued', 'Queued'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('In progress', 'In progress'), ('Canceled', 'Canceled'), ('Completed', 'Completed'), ('Partial', 'Partial'), ('Refunded', 'Refunded')], default='Queued', max_length=30, null=True, verbose_name='Status'),
        ),
    ]
