# Generated by Django 4.1.5 on 2023-03-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_ticket_options_alter_response_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('closed', 'closed'), ('pending', 'pending'), ('support answer', 'support answer'), ('user answer', 'user answer')], max_length=30, verbose_name='Status'),
        ),
    ]
